# Setup
title:               Machine Learning for Big Code and Naturalness
tagline:             'a survey'
description:         'A survey of research on machine learning for source code.'
url:                 https://ml4code.github.io
baseurl:             ''

collections:
  publications:
    output: true
    permalink: /:collection/:path/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
