# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Machine Learning for Code
tagline:             'a literature review'
description:         'A survey of academic research on machine learning models for source code.'
url:                 http://todo.com
baseurl:             ''

collections:
  publications:
    output: true
    permalink: /:collection/:path/
